#!/usr/bin/env bash
set -eo pipefail

# colors
RED=$(echo -en '\033[00;31m')
YELLOW=$(echo -en '\033[00;33m')

usage () {
    echo "Usage: kubectl idelete sts | statefulset | deploy | deployment <name> [-n|--namespace <namespace>]"
}

if [[ $# -eq 0 ]]; then
    usage
    exit 1
fi

# Get current k8s cluster and namespace
current_context=$(kubectl config current-context) || echo "error getting current context" && exit 1

current_namespace="$(kubectl config view -o=jsonpath="{.contexts[?(@.name==\"${current_context}\")].context.namespace}")" \
    || echo "error getting current namespace" && exit 1

if [[ -z $current_namespace ]]; then
    ns="default"
else
    ns=$current_namespace
fi

if [[ $3 ]]; then
    if [[ $3 == "-n" ]] || [[ $3 == "--namespace" ]]; then
        namespace_to_target=$4
    else
        echo "This option is not recognized"
        usage
        exit 1
    fi
fi

if [[ $1 == "statefulset" ]] || [[ $1 == "sts" ]]; then
    resource="sts"
elif [[ $1 == "deployment" ]] || [[ $1 == "deploy" ]]; then
    resource="deploy"
else
    echo "This plugin curently only supports sts | deploy deletion verification, exiting..."
    exit 1
fi

if [[ $namespace_to_target ]]; then
    ready_replicas=$(kubectl get $resource $2 -n $namespace_to_target -o jsonpath={'.status.readyReplicas'})
else
    ready_replicas=$(kubectl get $resource $2 -o jsonpath={'.status.readyReplicas'})
fi

echo "${RED}This $resource ($2) has $ready_replicas Running pods, do you want to proceed and delete it (only \"yes\" will be accepted)? This could disrupt the underlying application!"

# Display current k8s context (cluster) and namespace the resource is in
if [[ $namespace_to_target ]]; then
    echo "${YELLOW}Current k8s cluster: ${current_context}/$namespace_to_target"
else
    echo "${YELLOW}Current k8s cluster: ${current_context}/$ns"
fi

read user_input
if [[ $user_input == "yes" ]]; then
    # Pass the context for a safer deletion
    if [[ $namespace_to_target ]]; then
        kubectl --context $current_context delete $resource $2 -n $namespace_to_target
    else
        kubectl --context $current_context delete $1 $2
    fi
else
    echo "\e[0mAborting this $1 deletion"
    exit 1
fi
