#!/usr/bin/env bash
set -eo pipefail

# colors
RED=$(echo -en '\033[00;31m')
YELLOW=$(echo -en '\033[00;33m')

usage () {
    echo "Usage: kubectl idelete sts | statefulset | deploy | deployment <name> [-n | --namespace] <namespace>"
}

# Check if jq is installed
if ! [ $(command -v jq) ]; then
    echo "jq is not installed, exiting..."
    exit 1
fi

supported_resources=(
    "statefulset"
    "statefulsets"
    "sts"
    "deployment"
    "deployments"
    "deploy"
)

# Error handling
exit_err() {
   echo >&2 "${1}"
   exit 1
}

# Get current k8s cluster and namespace
current_context=$(kubectl config current-context) || exit_err "error getting current context"

# if [ !namespace ]; then
current_namespace="$(kubectl config view -o=jsonpath="{.contexts[?(@.name==\"${current_context}\")].context.namespace}")" \
    || exit_err "error getting current namespace"
# fi

if [ $# -eq 0 ]; then
    usage
    exit 0
fi

if [[ ${supported_resources[*]} != $1 ]]; then
    echo "This plugin curently only supports sts | deploy deletion verification, exiting..."
    exit 1
fi

# The namespace was not specifically provided, get the current namespace
if [ -z $3 ]; then
    if [[ -z $current_namespace ]]; then
        ns="default"
    else
        ns=$current_namespace
    fi
# Set the provided namespace
else
    if [ $3 == "-n" ] || [ $3 == "-namespace" ]; then
        if [ -z "$4" ]; then
            echo "Please provide a namespace"
            exit 1
        else
            namespace=$4
        fi
    else
        echo "This option is not supported"
        exit 1
    fi
fi

ready_replicas=$(kubectl get $1 $2 -ojson | jq -r '.status.readyReplicas')
echo "${RED}This $1 ($2) has $ready_replicas Running pods, do you want to proceed and delete it (y/n)? This could disrupt the underlying application!"
# Display current k8s context (cluster) and namespace (are you in a production environment?)
if [ ! $4 ]; then
    echo "${YELLOW}Current k8s cluster/namespace: ${current_context}/${ns}"
else
    echo "${YELLOW}Current k8s cluster/namespace: ${current_context}/${4}"
fi

read user_input
if [ $user_input == "y" ] || [ $user_input == "Y" ] || [ $user_input == "yes" ] || [ $user_input == "YES" ]; then
    # Pass the context for a safer sts deletion
    kubectl --context $current_context delete $1 $2
else
    echo "\e[0mAborting this $1 deletion"
    exit 1
fi
